### ISSUE TITLE
The toolchain isn't broken, your code is

### ISSUE THREAD

**Issue by mateoconlechuga** [KingDubDub/Jetpack-Joyride-CE#2]
This has to be the worst line of code I've ever seen: https://github.com/KingDubDub/Jetpack-Joyride-CE/blob/master/src/headers.h#L3

Learn how to write code properly, and read the coding guidelines so I don't have to repeat myself: https://ce-programming.github.io/toolchain/master/static/coding-guidelines.html

**Comment by mateoconlechuga** [comment]
If you aren't sure how to do things properly, ask. 99% of the time it is your code, not the toolchain.

**Comment by KingDubDub** [comment]
Will do, I've read the guidelines and I'll work on streamlining the mess I've made.

**Comment by KingDubDub** [comment]
It is done, it fixed the issues with the compilation of the header files but not with the latest toolchain, I did make sure that I had the latest clibs when I tested it.

**Comment by mateoconlechuga** [comment]
You made it 10000x worse. You need to *read* the guidelines again: https://ce-programming.github.io/toolchain/master/static/coding-guidelines.html#what-not-to-put-in-header-files

There is this point that explicitly says that you *should not do this in header files*:

> Variable declarations. If you need to have a “global variable” (you likely don’t), then the global variable should be declared in a source file and then included in the header using the extern keyword (e.g. extern global_variable[100];).

**Comment by mateoconlechuga** [comment]
Added comment to your Cemetech post. :) You need to check the return value of `gfx_MallocSprite` because it is crashing since the allocation is failing...
