### ISSUE TITLE
Downloading the file

### ISSUE THREAD

**Issue by greenfire7657** [KingDubDub/Jetpack-Joyride-CE#4]
I'm new to Github and just got my ti 84 plus ce and  i trying to look for a file on here that is compatible to texas instrument software to upload to my calculator but  there isn't a specific button  I know to press to download the file

**Comment by KingDubDub** [comment]
https://github.com/KingDubDub/Jetpack-Joyride-CE/releases

The big 'ol "Releases" tab on the main page, currently 0.20. I'll add a link to it in the README in the next update.

**Comment by greenfire7657** [comment]
iate this very much have a great day!
